### ISSUE TITLE
Support for concave Polygons

### ISSUE THREAD

**Issue by msteinbeck** [ArlindNocaj/Voronoi-Treemap-Library#5]
Is it, somehow, possible to render the Voronoi Treemap into a concave Polygon?

**Comment by ArlindNocaj** [comment]
You would have to add a function with can clip convex against non concave polygons and also implement what should happen when the region of a Voronoi cell gets disconnected due to the clipping.

**Comment by msteinbeck** [comment]
Could you give me a hint where I need to implement such a function?

**Comment by ArlindNocaj** [comment]
The VoronoiCore is the point where the iteration of moving the sites and clipping the polygon is started:
/src/kn/uni/voronoitreemap/core/VoronoiCore.java
More specifically the voroDiagram()  method.

Suggestion:
- Make an initial convex polygon (A) which is larger then your concave polygon (B).
- make sure the sites stay inside of the concave polygon while moving the sites.
- After clipping the cells with (A) clip them once more with polygon (B) at the end of the voroDiagram() method.

If its not clear what I mean, then you should read the paper:
https://www.uni-konstanz.de/mmsp/pubsys/publishedFiles/NoBr12a.pdf
